import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { parseCookies } from 'nookies';
import Head from 'next/head';
import Button from '@/components/Button';
import routes from '@/routes';
import Loader from '@/components/Loader';
import styles from '@/styles/Pages/ConfirmationPayment.module.css';
import checkToken from '@/services/checkToken';

export const getServerSideProps = async (context: any) => {
  const { token } = parseCookies(context);

  const tokenCheck = await checkToken(token);

  if (!tokenCheck.valid) {
    return tokenCheck;
  }

  return {
    props: {},
  };
};

function ConfirmationOrder() {
  const router = useRouter();
  const [seconds, setSeconds] = useState<number>(15);

  useEffect(() => {
    const intervalId = setInterval(() => {
      setSeconds((prevState) => prevState - 1);
    }, 1000);

    return () => {
      clearInterval(intervalId);
    };
  }, []);

  useEffect(() => {
    if (seconds === 0) {
      router.push(routes.home());
    }
  }, [seconds, router]);

  return (
    <main className={styles.main}>

      <Head>
        <title>The Bradery - Confirmation de votre commande</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Merci pour votre commande !</p>

      <p>
        Vous serez redirigez à l&apos;accueil dans
        {' '}
        {seconds}
        {' '}
        secondes
      </p>

      <Loader />

      <Button
        onClickAction={() => router.push(routes.home())}
      >
        Retourner à l&apos;accueil
      </Button>
    </main>
  );
}

export default ConfirmationOrder;
