import Head from 'next/head';
import React from 'react';
import { parseCookies } from 'nookies';
import styles from '@/styles/Pages/Orders.module.css';
import useGetOrders from '@/hooks/useGetOrders';
import checkToken from '@/services/checkToken';

export const getServerSideProps = async (context: any) => {
  const { token } = parseCookies(context);

  const tokenCheck = await checkToken(token);

  if (!tokenCheck.valid) {
    return tokenCheck;
  }

  return {
    props: {},
  };
};

function Orders() {
  const { ordersData, ordersIsLoading } = useGetOrders();
  const orders = !ordersIsLoading ? ordersData : [];

  return (
    <main className={styles.main}>
      <Head>
        <title>The Bradery - Produits </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.mainTitle}>Mes commandes</h1>

      <div className={styles.ordersContainer}>
        {orders.length > 0 ? (
          orders.map((order: any) => (
            <div
              className={styles.orderCard}
              key={order.id}
            >
              <p className={styles.orderTitle}>
                Commande n°
                {order.id}
              </p>

              <div className={styles.productRowsContainer}>
                {order.products.map((product: any) => (
                  <p>
                    {product.name}
                    {' '}
                    -
                    {' '}
                    {product.price}
                    €
                    {' '}
                    x
                    {product.quantity}
                  </p>
                ))}
              </div>

              <p className={styles.orderTotal}>
                Total :
                {' '}
                {order.total}
                €
              </p>

            </div>
          ))
        ) : (
          <p>Vous n&apos;avez actuellement réalisé aucune commande</p>
        )}
      </div>
    </main>
  );
}

export default Orders;
